### PR TITLE
Enabling logging in tests.

### PR DESCRIPTION
**Pull request by lvella**

### CODE REVIEW

**Comment by leonardoalt** [comment]
tests are failing :grimacing:

**Comment by leonardoalt** [comment]
Ohh yea I think the repo with shuffles was modified so we need to make a new use. I'll make a fork in our org and point there.

**Comment by leonardoalt** [comment]
so what does this PR actually do? I only see imports

**Comment by lvella** [comment]
> so what does this PR actually do? I only see imports

Replaces the macro #[test] with one that sets up `env_logger`, so that logging happens during tests, too.

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
